version: 1.1.{build}
os: Unstable
configuration: Release
environment:
  ModuleName: AudioDeviceCmdlets
  ApiKey:
    secure: y/mde3ZPuhXbecazSePa37KA2pNPUlZ6l+e+9uTMDebiQvEjkC1JqPXQ7Zrm541E
install:
- ps: >-

    Get-PackageProvider -Name NuGet -ForceBootstrap    
build:
  verbosity: minimal
skip_commits:
  message: /updated readme.*/
deploy_script:
- ps: >-

    $release = Join-Path -Path $ENV:APPVEYOR_BUILD_FOLDER -Childpath AudioDeviceCmdlets\bin\Release\*
    
    New-Item -Path C:\ -Name AudioDeviceCmdlets -Type Directory | out-null
    
    Copy-Item -path $release -destination C:\AudioDeviceCmdlets

    $PublishParams = @{
        Path = "C:\AudioDeviceCmdlets"
        NuGetApiKey = $ENV:ApiKey
    }

    $PublishParams
    
    #Publish!

    Publish-Module @PublishParams